engines:
  count: 2
  type: turboshaft
  engines:
    - name: engine_1
      max_power_kw: 452
      idle_ng_pct: 63.0
      max_ng_pct: 101.5
    - name: engine_2
      max_power_kw: 452
      idle_ng_pct: 63.0
      max_ng_pct: 101.5
