#pragma once
#ifndef TERRAIN_MODEL_H
#define TERRAIN_MODEL_H

#include <string>
#include <unordered_map>
#include <vector>
#include <cstdint>

// ---------------------------------------------------------------------------
// TerrainModel
// ---------------------------------------------------------------------------
// Loads SRTM3-format HGT tiles on demand and provides terrain elevation
// lookups with bilinear interpolation.
//
// Tile format (after maxpool_hgt.py — 6 arc-sec, max-pooled from 1 arc-sec source):
//   - 601 x 601 big-endian int16, metres MSL
//   - Row 0 = northern edge (lat+1), row 600 = southern edge (lat)
//   - Col 0 = western edge  (lon),   col 600 = eastern edge  (lon+1)
//   - Void/ocean samples = -32768 (returned as 0 m)
//   - Filename = SW-corner: N51E004.hgt
//   - Max-pooled: each pixel is the MAX of its 6×6 source block,
//     so terrain is never underestimated (safe for helicopter LOS checks)
//
// An LRU tile cache is maintained in memory (default 12 tiles, ~8 MB).
// ---------------------------------------------------------------------------
class TerrainModel
{
public:
    // tileDir: path to folder containing *.hgt files, e.g. "../terrain/srtm3/"
    explicit TerrainModel(const std::string& tileDir);

    // Returns terrain elevation in metres MSL at (lat, lon).
    // Returns 0.0 if the tile is not on disk (ocean / outside coverage)
    // or if the sample value is void (-32768).
    float getElevationM(double lat, double lon);

    // Convenience wrapper — returns elevation in feet.
    float getElevationFt(double lat, double lon);

    // Returns true if a terrain tile exists for this position.
    bool hasTile(double lat, double lon);

    bool isAvailable() const { return !mTileDir.empty(); }

private:
    // 6 arc-sec max-pooled tile dimensions (generated by maxpool_hgt.py)
    static const int  TILE_SIZE   = 601;
    static const int  TILE_PIXELS = TILE_SIZE * TILE_SIZE;
    static const int  VOID_VALUE  = -32768;
    static const size_t MAX_CACHE = 12;   // max tiles resident in RAM

    struct TileEntry {
        std::vector<int16_t> data;   // TILE_PIXELS values, host byte order
        uint64_t             lastAccess = 0;
    };

    std::string                               mTileDir;
    std::unordered_map<std::string, TileEntry> mCache;
    uint64_t                                  mAccessCounter = 0;

    static std::string makeKey     (int tileLat, int tileLon);
    static std::string makeFilename(int tileLat, int tileLon);

    // Returns pointer into cache (may load from disk).  nullptr = not found.
    const TileEntry* getTile(int tileLat, int tileLon);
    void             evictOldest();
};

#endif // TERRAIN_MODEL_H
